name = "IntervalMatrices"
uuid = "5c1f47dc-42dd-5697-8aaa-4d102d140ba9"
version = "0.2.1"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"

[compat]
julia = "≥ 1.0.0"
IntervalArithmetic = "≥ 0.14.0"
Reexport = "≥ 0.2.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
